# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: alveus
release:
  github:
    owner: ghostsquad
    name: alveus
env:
  - CGO_ENABLED=0
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    dir: ./cmd/alveus
    main: .
    ldflags: -s -w -X main.version={{.Version}}
    binary: alveus
archives:
  - formats: [ tar.gz ]
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README*
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:latest-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Tag }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .RawVersion }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ incpatch .Version }}-amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:latest-arm64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Tag }}-arm64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-arm64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .RawVersion }}-arm64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ incpatch .Version }}-amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghostsquad/alveus:latest
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:latest-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:latest-arm64
  - name_template: ghostsquad/alveus:{{ .Tag }}
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Tag }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Tag }}-arm64
  - name_template: ghostsquad/alveus:{{ .Major }}.{{ .Minor }}
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-arm64
  - name_template: ghostsquad/alveus:{{ incpatch .Version }}
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ incpatch .Version }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ incpatch .Version }}-arm64
  - name_template: ghostsquad/alveus:{{ .RawVersion }}
    image_templates:
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .RawVersion }}-amd64
      - gcr.io/ghostsquad/{{.ProjectName}}:{{ .RawVersion }}-arm64
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot-{{ .Commit }}"
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
universal_binaries:
  - # Whether to remove the previous single-arch binaries from the artifact list.
    # If left as false, your end release might have as much as three
    # archives for macOS: 'amd64', 'arm64' and 'all'.
    replace: true

    # Set the modified timestamp on the output binary, typically
    # you would do this to ensure a build was reproducible.
    # Pass an empty string to skip modifying the output.
    #
    # Templates: allowed.
    mod_timestamp: "{{ .CommitTimestamp }}"
