name: setup-demo
author: ghostsquad
description: sets up a demo KIND environment
inputs:
  cluster-name:
    description: the name of the KIND cluster
    default: testing
    required: false

runs:
  using: "composite"
  env:
    KIND_CLUSTER_NAME: ${{ inputs.cluster-name }}
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      with:
        version: 'v0.31.0'
        cluster_name: ${{ inputs.cluster-name }}
    - name: Install ArgoCD
      run: |-
        ./scripts/demo/install-argocd.sh
      shell: bash
