name: setup-demo
author: ghostsquad
description: sets up a demo KIND environment
inputs:
  cluster-name:
    description: the name of the KIND cluster
    default: testing
    required: false

outputs:
  port-forward-log:
    description: the path to the port-forward log file
    value: ${{ steps.install-argocd.outputs.port-forward-log }}

runs:
  using: "composite"
  steps:
    - uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      with:
        version: 'v0.31.0'
        cluster_name: ${{ inputs.cluster-name }}
    - name: Install ArgoCD
      id: install-argocd
      run: |-
        ./demo/install-argocd.sh
      shell: bash
      env:
        KIND_CLUSTER_NAME: ${{ inputs.cluster-name }}
