name: example-service-cluster-1
"on":
  workflow_dispatch: {}
concurrency:
  group: cluster-1
defaults:
  run:
    shell: bash
jobs:
  cluster-1:
    name: cluster-1
    runs-on:
    - ubuntu-latest
    environment:
      name: cluster-1
    env:
      ARGOCD_APPLICATION_FILE: fake-application-file.yaml
      ARGOCD_APPLICATION_NEW_TARGET_REVISION: 123new
      ARGOCD_URL: ""
      GIT_COMMIT_MESSAGE: "feat: 🚀 deploy to cluster-1"
    defaults:
      run:
        shell: bash
    steps:
    - uses: checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ""
    - name: git-config
      run: |-
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
    - uses: frenck/action-setup-yq@v1
    - name: update-application-yaml
      run: |-
        yq e '.spec.source.targetRevision = "${{ env.ARGOCD_APPLICATION_NEW_TARGET_REVISION }}"' \
        '${ARGOCD_APPLICATION_FILE}'
    - name: git-add-commit
      run: |-
        git add "${ARGOCD_APPLICATION_FILE}"
        git commit -m "${GIT_COMMIT_MESSAGE}"
    - uses: actions-js/push@v1.5
      with:
        branch: ""
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: argocd-login
      run: argocd login "${ARGOCD_URL}" --grpc-web --skip-test-tls
    - name: argocd-upsert
      run: |-
        argocd app create --upsert --file "${ARGOCD_APPLICATION_FILE}" \
          --grpc-web \
          --sync-retry-backoff-factor 2 \
          --sync-retry-backoff-max-duration 3m0s \
          --sync-retry-limit 2 \
          ;
