name: example-service
"on":
  workflow_dispatch: {}
  push:
    paths:
    - ./examples/example-service/manifests
    branches:
    - main
jobs:
  staging:
    name: staging
    uses: .github/workflows/example-service-staging.yml
