concurrency:
  group: cluster-1
defaults:
  run:
    shell: bash
jobs:
  cluster-1:
    defaults:
      run:
        shell: bash
    env:
      ARGOCD_APPLICATION_FILE: fake-application-file.yaml
      ARGOCD_APPLICATION_NEW_TARGET_REVISION: 123new
      ARGOCD_URL: ""
      GIT_COMMIT_MESSAGE: "feat: \U0001F680 deploy to cluster-1"
    environment:
      name: cluster-1
    name: cluster-1
    runs-on:
    - ubuntu-latest
    steps:
    - uses: checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ""
    - name: git-config
      run: "\n\t\t\t\t\tgit config --global user.name \"${{ github.actor }}\"\n    \t\t\tgit
        config --global user.email \"${{ github.actor }}@users.noreply.github.com\"\n"
    - uses: frenck/action-setup-yq@v1
    - name: update-application-yaml
      run: |2

        yq e '.spec.source.targetRevision = "${{ env.ARGOCD_APPLICATION_NEW_TARGET_REVISION }}"' "${ARGOCD_APPLICATION_FILE}"
    - name: git-add-commit
      run: |2

        git add "${ARGOCD_APPLICATION_FILE}"
        git commit -m "${GIT_COMMIT_MESSAGE}"
    - uses: actions-js/push@v1.5
      with:
        branch: ""
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: argocd-login
      run: |2

        argocd login "${ARGOCD_URL}" --grpc-web --skip-test-tls
    - name: argocd-upsert
      run: "\nargocd app create --upsert --file \"${ARGOCD_APPLICATION_FILE}\" \\\n\t--grpc-web
        \\\n\t--sync-retry-backoff-factor 2 \\\n\t--sync-retry-backoff-max-duration
        3m0s \\\n\t--sync-retry-limit 2 \\\n\t;\n"
name: example-service-cluster-1
"on":
  workflow_dispatch: {}
