jobs:
  staging:
    name: staging
    secrets:
      inherit: true
    uses: ./.github/workflows/alveus-example-service-staging.yml
name: example-service
"on":
  push:
    branches:
    - main
    paths:
    - .alveus/demo/manifests
  workflow_dispatch: {}
