name: example-service
"on":
  workflow_dispatch: {}
  push:
    paths:
    - ../../../demo/manifests
    branches:
    - main
jobs:
  staging:
    name: staging
    uses: .github/workflows/alveus-example-service-staging.yml
