name: app-update
author: ghostsquad
description: updates all applications
inputs:
  target-revision:
    description: The target revision to deploy
    required: true
  alveus-file:
    description: The path to the alveus YAML file
    required: true
  destination-group:
    description: The name of the destination group to update
    required: true
  namespace:
    description: Namespace to use. If empty, application will not be modified
  commit-message:
    description: The git commit message to use when the application is updated
    default: "chore: deploy"
  branch:
    description: Remote branch name where commit is going to be pushed to. Defaults to the current branch.
  commit-options:
    description: Options used by `git-commit`. See https://git-scm.com/docs/git-commit#_options
  repository:
    description: Local file path to the repository. Defaults to the root of the repository.
  commit-user-name:
    description: defaults to "github-actions[bot]
  commit-user-email:
    description: defaults to "41898282+github-actions[bot]@users.noreply.github.com"
  commit-author:
    description: |-
      defaults to "username <numeric_id+username@users.noreply.github.com>", 
      where "numeric_id" and "username" belong to the author of the commit that triggered the run
  tag-name:
    description: |-
      Tag name to be created in the local repository and pushed to the remote repository on the defined branch.
      If only one of `tag_name` or `tagging_message` is provided, the value of the provided field will be used for both tag name and message.
  tagging-message:
    description: |-
      Message to annotate the created tag with.
      If only one of `tag_name` or `tagging_message` is provided, the value of the provided field will be used for both tag name and message.
  status-options:
    description: |-
      Option used by `git-status` to determine if the repository is dirty.
      See https://git-scm.com/docs/git-status#_options
  add-options:
    description: |-
      Options used by `git-add`.
      See https://git-scm.com/docs/git-add#_options
  push-options:
    description: |-
      Options used by `git-push`.
      See https://git-scm.com/docs/git-push#_options
  create-branch:
    description: Create given branch name in local and remote repository.

runs:
  using: "composite"
  steps:
    - uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
    - name: get destination group data
      id: get-destination-group-data
      shell: bash
      run: |-
        filename=${{ runner.temp }}/applications.json
        echo 'destination-group: ${{ inputs.destination-group }}'
        destination_data=$(yq '.${{ inputs.destination-group }} | to_entries' '${{ inputs.alveus-file }}')
        echo "${destination_data}"
        destination_data_b64=$(echo -n "${destination_data}" | base64)
        echo "value-b64=${destination_data_b64}" >> $GITHUB_OUTPUT
    - name: update-application-yaml
      shell: bash
      run: |-
        group_data_b64='${{ steps.get-group-data.outputs.value-64 }}'
        group_data=$(echo "${group_data_b64}" | base64 --decode)
        
        echo "<DEBUG>"
        echo ""
        cat "${group_data}"
        echo ""
        echo "</DEBUG>"
        
        readarray -t group_data_entries < <(echo "${group_data}" | jq --compact-output '. | to_entries')
        
        for item in "${group_data_entries[@]}"; do
          application_file=$(jq --raw-output '.applicationFile' <<< "$item")
          echo "updating application file: ${application_file}..."
          yq e -i '.spec.source.targetRevision = "${{ inputs.target-revision }}"' \
            "${application_file}"

          if [ -n '${{ inputs.namespace }}' ]; then
            yq e -i '.spec.destination.namespace = "${{ inputs.namespace }}"' \
            "${application_file}"
          fi
        done
    - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
        commit_options: ${{ inputs.commit-options }}
        repository:
        commit_user_name: ${{ inputs.commit-user-name }}
        commit_user_email: ${{ inputs.commit-user-email }}
        commit_author: ${{ inputs.commit-author }}
        tag_name: ${{ inputs.tag-name }}
        tagging_message: ${{ inputs.tagging-message }}
        status_options: ${{ inputs.status-options }}
        add_options: ${{ inputs.add-options }}
        push_options: ${{ inputs.push-options }}
        create_branch: ${{ inputs.create-branch }}
