name: app-update
author: ghostsquad
description: updates all applications
inputs:
  target-revision:
    description: The target revision to deploy
    required: true
  applications:
    description: JSON list of application files to update (mutually exclusive with `applications-file`)
  applications-file:
    description: a JSON file that contains a list of applications to update (mutually exclusive with `applications`)
  namespace:
    description: Namespace to use. If empty, application will not be modified
  commit-message:
    description: The git commit message to use when the application is updated
    default: "chore: deploy"
  branch:
    description: Remote branch name where commit is going to be pushed to. Defaults to the current branch.
  commit-options:
    description: Options used by `git-commit`. See https://git-scm.com/docs/git-commit#_options
  repository:
    description: Local file path to the repository. Defaults to the root of the repository.
  commit-user-name:
    description: defaults to "github-actions[bot]
  commit-user-email:
    description: defaults to "41898282+github-actions[bot]@users.noreply.github.com"
  commit-author:
    description: |-
      defaults to "username <numeric_id+username@users.noreply.github.com>", 
      where "numeric_id" and "username" belong to the author of the commit that triggered the run
  tag-name:
    description: |-
      Tag name to be created in the local repository and pushed to the remote repository on the defined branch.
      If only one of `tag_name` or `tagging_message` is provided, the value of the provided field will be used for both tag name and message.
  tagging-message:
    description: |-
      Message to annotate the created tag with.
      If only one of `tag_name` or `tagging_message` is provided, the value of the provided field will be used for both tag name and message.
  status-options:
    description: |-
      Option used by `git-status` to determine if the repository is dirty.
      See https://git-scm.com/docs/git-status#_options
  add-options:
    description: |-
      Options used by `git-add`.
      See https://git-scm.com/docs/git-add#_options
  push-options:
    description: |-
      Options used by `git-push`.
      See https://git-scm.com/docs/git-push#_options
  create-branch:
    description: Create given branch name in local and remote repository.

runs:
  using: "composite"
  steps:
    - uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
    - name: get-applications
      id: get-applications
      shell: bash
      run: |-
        if [ -n '${{ inputs.applications-file }}' ]; then
          echo 'applications-file=${{ inputs.applications-file }}' >> $GITHUB_OUTPUT
          exit 0
        fi
        
        if [ -n '${{ inputs.applications }}' ]; then
          filename=${{ runner.temp }}/applications.json
          echo '${{ inputs.applications }}' > "${filename}"
          echo "applications-file=${filename}" >> $GITHUB_OUTPUT
        fi
    - name: update-application-yaml
      shell: bash
      run: |-
        readarray -t applications < <(jq --compact-output '.[]' '${{ steps.get-applications.outputs.applications-file }}')
        
        for item in "${applications[@]}"; do
          application_file=$(jq --raw-output '.' <<< "$item")
          echo "updating application file: ${application_file}..."
          yq e -i '.spec.source.targetRevision = "${{ inputs.target-revision }}"' \
            '${application_file}'
        
          if [ -n "${{ inputs.namespace }}" ]; then
            yq e -i '.spec.destination.namespace = "${{ inputs.namespace }}"' \
            '${application_file}'
          fi
        done
    - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
        commit_options: ${{ inputs.commit-options }}
        repository:
        commit_user_name: ${{ inputs.commit-user-name }}
        commit_user_email: ${{ inputs.commit-user-email }}
        commit_author: ${{ inputs.commit-author }}
        tag_name: ${{ inputs.tag-name }}
        tagging_message: ${{ inputs.tagging-message }}
        status_options: ${{ inputs.status-options }}
        add_options: ${{ inputs.add-options }}
        push_options: ${{ inputs.push-options }}
        create_branch: ${{ inputs.create-branch }}

